### ISSUE TITLE
Deprecation of using `go get`

### ISSUE THREAD

**Issue by hansmannj** [unprofession-al/scum#6]
Since the use of `go get` is deprecated (https://go.dev/doc/go-get-install-deprecation), the `go.mod` needs to be updated in order to work with `go install` as e.g. `go install github.com/unprofession-al/scum@latest`.
Currently this throws:
```bash
module declares its path as: scum
	        but was required as: github.com/unprofession-al/scum
```

This PR https://github.com/unprofession-al/scum/pull/5 should fix this issue and would make the installation of scum in our ansible repo easier.

It would be nice if you could have a look at it and, if you agree, approve it.
Thanks a lot and liebe Grüsse
Jürgen

**Comment by sontags** [comment]
Salut Jürgen,

Hope you are doing well?! Your PR have been merged, thanks for that!

Cheers,
Daniel

**Comment by hansmannj** [comment]
Salut Dani

Thanks for merging :-)
And yes, thanks, I'm doing well.
Hope you likewise? How are things for you?

Cheers
Jürgen
